// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

/// <reference types="node"/>  
//! Specifies the use of node types since my file structure is a little outta wack its throwing the ts.conf into a panic.

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL!
  },
});
